# Generated by Django 5.0.4 on 2024-04-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_institution_user_is_organization_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
    ]
