# Generated by Django 5.0.4 on 2024-06-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_birth_date_remove_user_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee'), ('teacher', 'teacher'), ('student', 'student'), ('parent', 'parent'), ('publisher', 'publisher')], max_length=15),
        ),
    ]
