# Generated by Django 5.0.4 on 2024-06-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_superuser_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='publisher',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
