# Generated by Django 4.0.2 on 2024-09-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_employee_special_role'),
        ('institutions', '0034_alter_organization_next_payment_date'),
        ('events', '0002_agegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroupActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.activity')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_group_activities', to='events.agegroup')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_age_groups', to='employees.employee')),
            ],
        ),
    ]
