# Generated by Django 4.0.2 on 2024-09-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0034_alter_organization_next_payment_date'),
        ('events', '0006_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='institution',
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.organization'),
        ),
    ]
