# Generated by Django 4.0.2 on 2024-09-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_institution_event_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='academic_year',
        ),
    ]
