# Generated by Django 5.0.4 on 2024-06-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancegroup',
            name='institution',
        ),
    ]
