# Generated by Django 5.0.4 on 2024-05-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0018_alter_class_grade_alter_class_students'),
        ('students', '0004_studentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.grade'),
        ),
    ]
