# Generated by Django 5.0.4 on 2024-05-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
