# Generated by Django 5.0.4 on 2024-05-06 07:01

import nanoid.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='invitation_code',
            field=models.CharField(blank=True, default=nanoid.generate(), max_length=50, null=True),
        ),
    ]
