# Generated by Django 5.0.4 on 2024-05-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='invitation_code',
            field=models.CharField(blank=True, default='gLfby6b0cCDlza-roPvD', max_length=50, null=True),
        ),
    ]
