# Generated by Django 5.0.4 on 2024-06-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_studenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.studenttype'),
        ),
    ]
