# Generated by Django 5.0.4 on 2024-04-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='organization',
        ),
    ]
