# Generated by Django 5.0.4 on 2024-04-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
