# Generated by Django 5.0.4 on 2024-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
