# Generated by Django 4.0.2 on 2024-08-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='special_role',
            field=models.CharField(blank=True, choices=[('bursar', 'bursar'), ('librarian', 'librarian')], max_length=50, null=True),
        ),
    ]
