# Generated by Django 4.0.2 on 2024-09-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_admin',
        ),
    ]
