# Generated by Django 4.0.2 on 2024-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_remove_employee_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='special_role',
            field=models.CharField(blank=True, choices=[('bursar', 'bursar'), ('librarian', 'librarian'), ('admin', 'admin')], max_length=50, null=True),
        ),
    ]
