# Generated by Django 4.0.2 on 2024-09-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employee_special_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='special_role',
            field=models.CharField(blank=True, choices=[('bursar', 'bursar'), ('librarian', 'librarian')], max_length=50, null=True),
        ),
    ]
