# Generated by Django 5.0.4 on 2024-05-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_chargetypes'),
        ('institutions', '0019_alter_class_students_period'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChargeTypes',
            new_name='ChargeType',
        ),
    ]
