# Generated by Django 5.0.4 on 2024-05-29 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_chargetypes_chargetype'),
        ('institutions', '0019_alter_class_students_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.chargetype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.organization')),
            ],
        ),
    ]
