# Generated by Django 5.0.4 on 2024-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('void', 'Void')], default='due', max_length=10),
        ),
    ]
