# Generated by Django 5.0.4 on 2024-06-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargetype',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='organization',
        ),
    ]
