# Generated by Django 5.0.4 on 2024-06-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_chargetype_organization_and_more'),
        ('institutions', '0026_alter_classsubject__class'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.terms'),
        ),
    ]
