# Generated by Django 5.0.4 on 2024-05-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_group',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='registry.attendancegroup'),
            preserve_default=False,
        ),
    ]
