# Generated by Django 5.0.4 on 2024-05-06 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_attendance_attendance_group'),
        ('institutions', '0019_alter_class_students_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField()),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.classsubject')),
            ],
        ),
    ]
