# Generated by Django 5.0.4 on 2024-05-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_assignment_created_at_assignment_updated_at_exam'),
        ('institutions', '0019_alter_class_students_period'),
        ('students', '0013_alter_student_invitation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam')], max_length=100)),
                ('assessment_type_id', models.PositiveIntegerField()),
                ('max_marks', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.classsubject')),
                ('marking_criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.markingcriterion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
