# Generated by Django 5.0.4 on 2024-05-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='assessment_type_id',
            new_name='assessment_id',
        ),
    ]
