# Generated by Django 5.0.4 on 2024-06-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_rename_assessment_type_id_mark_assessment_id'),
        ('institutions', '0023_remove_academicyear_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='academic_year',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='institutions.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='institutions.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='institutions.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='academic_year',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='institutions.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='academic_year',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='institutions.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markingcriterion',
            name='academic_year',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='institutions.academicyear'),
            preserve_default=False,
        ),
    ]
