# Generated by Django 5.0.4 on 2024-06-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_assignment_academic_year_attendance_academic_year_and_more'),
        ('institutions', '0026_alter_classsubject__class'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.terms'),
        ),
    ]
