# Generated by Django 5.0.4 on 2024-06-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_attendance_term'),
        ('institutions', '0026_alter_classsubject__class'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.terms'),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.terms'),
        ),
        migrations.AddField(
            model_name='mark',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.terms'),
        ),
    ]
