# Generated by Django 5.0.4 on 2024-06-23 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_assignment_term_exam_term_mark_term'),
        ('institutions', '0026_alter_classsubject__class'),
        ('students', '0015_student_student_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.classsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.terms')),
            ],
        ),
    ]
