# Generated by Django 4.0.2 on 2024-08-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_termresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_academic_year', models.BooleanField(default=True)),
            ],
        ),
    ]
