# Generated by Django 4.0.2 on 2024-08-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
