# Generated by Django 4.0.2 on 2024-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_exam_end_exam_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start',
            field=models.TimeField(),
        ),
    ]
