# Generated by Django 4.0.2 on 2024-09-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_alter_exam_end_alter_exam_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termresult',
            name='notes',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
