# Generated by Django 5.0.4 on 2024-06-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0002_publisheruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisheruser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='publisheruser',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
