# Generated by Django 5.0.4 on 2024-06-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0003_rename_name_publisheruser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisheruser',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
