# Generated by Django 5.0.4 on 2024-06-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0004_alter_publisheruser_invitation_code'),
        ('institutions', '0026_alter_classsubject__class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=5000)),
                ('author', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('image', models.TextField(blank=True, max_length=1000, null=True)),
                ('book_url', models.TextField(max_length=1000)),
                ('unit_sold', models.PositiveIntegerField(default=0)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.grade')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.level')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_shop.publisher')),
            ],
        ),
    ]
