# Generated by Django 4.0.2 on 2024-07-07 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0033_alter_institution_organization'),
        ('book_shop', '0008_book_isbn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.subject'),
        ),
    ]
