# Generated by Django 5.0.4 on 2024-04-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_organization_created_at_organization_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='main_controller',
        ),
    ]
