# Generated by Django 5.0.4 on 2024-04-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='colors',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='class',
            name='max_assignments_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='max_exams_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='max_period_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
