# Generated by Django 5.0.4 on 2024-04-23 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.class'),
        ),
    ]
