# Generated by Django 5.0.4 on 2024-04-23 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_classsubject__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.class'),
        ),
    ]
