# Generated by Django 5.0.4 on 2024-04-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_alter_classsubject__class'),
        ('students', '0004_studentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='students.student'),
        ),
    ]
