# Generated by Django 5.0.4 on 2024-04-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_class_teacher_alter_classsubject_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='teacher',
            new_name='class_teacher',
        ),
    ]
