# Generated by Django 5.0.4 on 2024-04-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_computers', models.PositiveIntegerField(blank=True, null=True)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_smart_board', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='institutions.institution')),
            ],
        ),
    ]
