# Generated by Django 5.0.4 on 2024-05-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0017_room'),
        ('students', '0004_studentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.grade'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='students.student'),
        ),
    ]
