# Generated by Django 5.0.4 on 2024-06-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0024_remove_grade_institution_remove_level_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='institution',
        ),
    ]
