# Generated by Django 5.0.4 on 2024-06-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0025_remove_subject_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='institutions.class'),
        ),
    ]
