# Generated by Django 5.0.4 on 2024-06-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0026_alter_classsubject__class'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
