# Generated by Django 5.0.4 on 2024-06-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0027_organization_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_frequency',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
