# Generated by Django 5.0.4 on 2024-06-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0028_organization_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
