# Generated by Django 5.0.4 on 2024-06-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0029_organization_next_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_invoice_generated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
