# Generated by Django 4.0.2 on 2024-07-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_student_type'),
        ('institutions', '0031_institution_district_institution_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='group',
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='students.Student'),
        ),
    ]
