# Generated by Django 4.0.2 on 2024-07-07 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0032_remove_grade_group_alter_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='institutions.organization'),
        ),
    ]
